/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export default function ThreeDAvatarModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/sampleavatar.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <Canvas>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Armature">
            <skinnedMesh
              name="Avatia_Bottom"
              geometry={nodes.Avatia_Bottom.geometry}
              material={materials.UnionAvatars_Bottom}
              skeleton={nodes.Avatia_Bottom.skeleton}
            />
            <group name="Avatia_Hand1">
              <skinnedMesh
                name="Object_0001"
                geometry={nodes.Object_0001.geometry}
                material={materials.hand_lowpoly}
                skeleton={nodes.Object_0001.skeleton}
              />
              <skinnedMesh
                name="Object_0001_1"
                geometry={nodes.Object_0001_1.geometry}
                material={materials.nail_lowpoly}
                skeleton={nodes.Object_0001_1.skeleton}
              />
            </group>
            <group name="Avatia_Hand2">
              <skinnedMesh
                name="Object_0002"
                geometry={nodes.Object_0002.geometry}
                material={materials.hand_lowpoly}
                skeleton={nodes.Object_0002.skeleton}
              />
              <skinnedMesh
                name="Object_0002_1"
                geometry={nodes.Object_0002_1.geometry}
                material={materials.nail_lowpoly}
                skeleton={nodes.Object_0002_1.skeleton}
              />
            </group>
            <group name="Avatia_Head">
              <skinnedMesh
                name="Mesh001"
                geometry={nodes.Mesh001.geometry}
                material={materials["FaceTexture1.001"]}
                skeleton={nodes.Mesh001.skeleton}
                morphTargetDictionary={nodes.Mesh001.morphTargetDictionary}
                morphTargetInfluences={nodes.Mesh001.morphTargetInfluences}
              />
              <skinnedMesh
                name="Mesh001_1"
                geometry={nodes.Mesh001_1.geometry}
                material={materials["AvatarTeethLower.001"]}
                skeleton={nodes.Mesh001_1.skeleton}
                morphTargetDictionary={nodes.Mesh001_1.morphTargetDictionary}
                morphTargetInfluences={nodes.Mesh001_1.morphTargetInfluences}
              />
              <skinnedMesh
                name="Mesh001_2"
                geometry={nodes.Mesh001_2.geometry}
                material={materials["AvatarTeethUpper.001"]}
                skeleton={nodes.Mesh001_2.skeleton}
                morphTargetDictionary={nodes.Mesh001_2.morphTargetDictionary}
                morphTargetInfluences={nodes.Mesh001_2.morphTargetInfluences}
              />
            </group>
            <group name="Avatia_Shoes">
              <skinnedMesh
                name="007-0-7"
                geometry={nodes["007-0-7"].geometry}
                material={materials.UnionAvatars_Shoes}
                skeleton={nodes["007-0-7"].skeleton}
              />
              <skinnedMesh
                name="007-0-7_1"
                geometry={nodes["007-0-7_1"].geometry}
                material={materials.UnionAvatars_Shoes_laces}
                skeleton={nodes["007-0-7_1"].skeleton}
              />
            </group>
            <skinnedMesh
              name="Avatia_Upper"
              geometry={nodes.Avatia_Upper.geometry}
              material={materials["Wolf3D_Outfit_Top.001"]}
              skeleton={nodes.Avatia_Upper.skeleton}
            />
            <primitive object={nodes.Hips} />
            <primitive object={nodes.neutral_bone} />
          </group>
        </group>
      </group>
    </Canvas>
  );
}

useGLTF.preload("/sampleavatar.glb");
